### ISSUE TITLE
Add a better explanation of the parameter type for the sync API

### ISSUE THREAD

**Issue by realityking** [contentful/slash-developers#100]
The extend of the current documentation is here: http://docs.contentfulcda.apiary.io/#reference/synchronization/initial-synchronisation-of-entries-of-a-specific-content-type/query-entries?console=1

The parameter is only implicitly explained and there's no list of what values are valid. (Mentioned are `Entry `, `Deletion` and `DeletedEntry`, but I'm assuming there are also some for Assets)

**Comment by neonichu** [comment]
There's a list a bit above here: <https://github.com/contentful/slash-developers/blob/master/apiary/cda-body.apib#L707> — might make sense to link back or maybe merge the two?

**Comment by realityking** [comment]
Duh. Probably still a good idea to make it a table. (IMO that's more readable)

**Comment by gaapt** [comment]
Also, there is an introductory page at

https://www.contentful.com/developers/docs/concepts/sync/

It would probably make sense to consolidate everything into a single reference, similar to Links at https://www.contentful.com/developers/docs/concepts/links/

**Comment by neonichu** [comment]
I think it makes sense to keep the table inside the blueprint, because it is reference material.

**Comment by gaapt** [comment]
Created https://github.com/contentful/slash-developers/pull/119
