### ISSUE TITLE
Clarify differences in CMA and CDA responses

### ISSUE THREAD

**Issue by gaapt** [contentful/slash-developers#104]
Although we clearly state that:

>If you want to deliver content (e.g. to the web or to mobile apps) use the Content Delivery API. The Content Management API is meant to be used only for managing content, not delivering it.

Some users still use CMA for GET requests, which has a very different structure from CDA responses.

**Comment by grncdr** [comment]
I agree we should clarify that the CMA responses will have a different structure. However, using the CMA for GET requests makes perfect sense, if that request is part of some content management process.

**Comment by gaapt** [comment]
Created https://github.com/contentful/slash-developers/pull/137
