### ISSUE TITLE
Fix blueprints to work with latest release of drafter / dredd

### ISSUE THREAD

**Issue by neonichu** [contentful/slash-developers#149]
Seems like arrays are assumed to be objects now by default and specifying the type explicitly leads to an error: 

```diff
diff --git a/apiary/_partials/delivery-and-preview-data-structures.apib b/apiary/_partials/delivery-and-preview-data-structures.apib
index 51680e6..c36d6b0 100644
--- a/apiary/_partials/delivery-and-preview-data-structures.apib
+++ b/apiary/_partials/delivery-and-preview-data-structures.apib
@@ -25,7 +25,7 @@
 
 ### Content Type
 
-- fields (array[object]) - Fields
+- fields (array) - Fields
     - (object)
         - id: name
         - name: Name
```

Let's wait until apiaryio/protagonist#113 trickles down into a new `dredd` release, though, before we change anything.

**Comment by grncdr** [comment]
@neonichu there has been a new release of protagonist (1.2.3) that should be picked up by dredd's package.json https://github.com/apiaryio/dredd/blob/master/package.json#L37, so I think we're good to go ahead and make this change now.

**Comment by neonichu** [comment]
I'm still seeing some remaining issues locally when using protagonist 1.2.3, will notify upstream.

**Comment by neonichu** [comment]
Parsing the CMA blueprint actually crashes `drafter` right now, see apiaryio/drafter#207
