### ISSUE TITLE
Document validations in CMA blueprint

### ISSUE THREAD

**Issue by neonichu** [contentful/slash-developers#153]
There's a TODO item inside the blueprint itself for this :) <https://github.com/contentful/slash-developers/blob/master/apiary/cma.apib#L234>

A list of supported validations can be found on our internal Wiki: <https://contentful.atlassian.net/wiki/display/ENG/Validations>

**Comment by gaapt** [comment]
PR https://github.com/contentful/slash-developers/pull/187

**Comment by neonichu** [comment]
Fixed by  #187
