### ISSUE TITLE
Change "cfexampleapi" space to use random IDs

### ISSUE THREAD

**Issue by neonichu** [contentful/slash-developers#16]
While the original idea of making the IDs on that space more readable is admirable, this leads to users expecting that queries support using content type names. This has been the number one problem coming up in support requests that I had to answer, so it seems to me that we should finally change it.

@grncdr opinions?

**Comment by neonichu** [comment]
Yet another instance of this: contentful/contentful-management.objc#8

**Comment by grncdr** [comment]
> @grncdr opinions?

We're actually aiming to make content type ID's readable-by-default (derived from the content type name) in the not too distant future. However, there are still going to be all of the existing content types with auto-generated ID's, so I'd be fine with changing it, then possibly changing it back in the future.

**Comment by rbarisic** [comment]
This should be stated exactly like that in the docs.  That's why you have documentation versioning. You can inform people that this will change in the future, but the current doc should correspond to the current functionality. Don't get caught in a situation like PHP.

**Comment by neonichu** [comment]
@rbarisic The random IDs are merely the default, you're able to choose readable ones already if you use the CMA to create entries (see [this](http://docs.contentfulcma.apiary.io/#reference/entries/entry/create/update-an-entry). The issue here is that the example space uses such readable IDs, which can lead to the confusion mentioned above.

**Comment by grncdr** [comment]
We've (finally) released this change for newly created Content Types, so I'm closing this issue.

**Comment by neonichu** [comment]
:tada:
