### ISSUE TITLE
Clarify equality operator for custom vs. sys fields

### ISSUE THREAD

**Issue by neonichu** [contentful/slash-developers#163]
We currently have an example query for exact matches with uses `sys.id` and therefore is not constrained on the content type: <https://github.com/contentful/slash-developers/blob/master/apiary/_partials/delivery-and-preview-resources.apib#L246-L256>. The documented query for `fields` is using an array value (<https://github.com/contentful/slash-developers/blob/master/apiary/_partials/delivery-and-preview-resources.apib#L284-L293>). This might be confusing for readers as they might think the usage of the `content_type` constraint is related to the array value somehow. We should make it clear when the `content_type` constraint is required and when it isn't.

**Comment by grncdr** [comment]
IIRC there are already a couple of notes here and there in the docs, but a little repetition never hurts. @neonichu want to create a quick PR that clarifies this in all of the entry querying examples?

**Comment by neonichu** [comment]
Can do, would adopt this note:

> Note that when ordering Entries by fields you must set the `content_type` URI query parameter to the ID of the Content Type you want to filter by.
