### ISSUE TITLE
Improve explanation of revision

### ISSUE THREAD

**Issue by trodrigues** [contentful/slash-developers#169]
In https://www.contentful.com/developers/docs/references/content-delivery-api/#/introduction/common-resource-attributes the `revision` attribute is explained as 'Version of resource'.

We should perhaps improve this and explain it as 'Published version of resource'. Also we could maybe add a paragraph below with a better explanation, stating that this maps to the published version exposed by the CMA.

**Comment by gaapt** [comment]
Opened https://github.com/contentful/slash-developers/pull/178
