### ISSUE TITLE
Links documentation is hard to find in CDA docs

### ISSUE THREAD

**Issue by trodrigues** [contentful/slash-developers#171]
While we have documented links on the [developer center](https://www.contentful.com/developers/docs/concepts/links/), when people land on the [CDA docs](https://www.contentful.com/developers/docs/references/content-delivery-api/) (or if they might not even be looking for the links in the developer center), it's not easy to find information about links and the includes array.

This is because this information is buried under the "search parameters" section.

Information about Links should probably be easier to find, under its own top level menu.

**Comment by grncdr** [comment]
Agreed, @gaapt could you bring this information up to it's own section in the docs? Should go just before the "Search Parameters" section, at the same level.

**Comment by gaapt** [comment]
Created https://github.com/contentful/slash-developers/pull/192
