### ISSUE TITLE
Search parameters CDA docs menu is noisy and confusing

### ISSUE THREAD

**Issue by trodrigues** [contentful/slash-developers#172]
This is what the "search parameters" sub menu currently looks like:

![2016-01-20 at 10 05](https://cloud.githubusercontent.com/assets/38177/12444146/60e4c5c8-bf5d-11e5-8473-97bc6801a62a.png)

The bar in itself is too narrow, and some of the titles are too long.

**Comment by neonichu** [comment]
As far as I can see, we cannot control the width of the sidebar (<http://embed.apiary.io/api-reference.html#theme-properties>), so we'll have to shorten the titles only.

**Comment by grncdr** [comment]
The bar width is definitely something we can't effect (was looked into by @gaapt already).

Regarding the titles, suggestions are very welcome!

**Comment by gaapt** [comment]
Some titles are clearly too big and confusing. 

>The inequality operator can be used to look for fields that don't match a specific value

**Comment by grncdr** [comment]
@gaapt can you rework these titles to be shorter and open a PR please?

**Comment by trodrigues** [comment]
Did some on #177
