### ISSUE TITLE
Bounding Box Location example parameter are twisted

### ISSUE THREAD

**Issue by mariobodemann** [contentful/slash-developers#173]
https://github.com/contentful/slash-developers/blob/383a42b74f2047820edfb2a71c5af3526d956386/apiary/_partials/delivery-and-preview-resources.apib#L490

The rectangle parameter should read `40,-124,36,-121`, instead of `36,-124,40,-121` otherwise an invalid rectangle gets generated, and an empty result returned, instead of the expected *San Francisco* entry.

Also replacing left/right/top/down with West/East/North/South, clarifies usage for location based searches.

**Comment by gaapt** [comment]
I created https://github.com/contentful/slash-developers/pull/184, but waited to replace left/right/top/down with West/East/North/South.

As the values refer to the coordinates of two corners of a rectangle, don't you think it might become confusing?

**Comment by mariobodemann** [comment]
Hey,

I was just thinking, since you refer to angles on a sphere, maybe something
like north east south west would be easier to understand, since it is not
necessarily a rectangular area you are describing (think of an area close
to the north/south pole: Where is up?) But if it is already to confusing, I
am fine with not changing the naming, as long as the sample now is curlable
... :)


Mario

**Comment by neonichu** [comment]
We can close this as #184 has been merged.
