### ISSUE TITLE
Deactivate links to "self" in API references

### ISSUE THREAD

**Issue by floelhoeffel** [contentful/slash-developers#194]
When in one of the API references, the navigation does link to "self" while that link should be deactivated.

e.g. when on 

https://www.contentful.com/developers/docs/references/content-delivery-api/#/reference

the top link

[cda-reference]:https://www.contentful.com/developers/docs/references/content-delivery-api

should not be clickable and active instead.

**Comment by neonichu** [comment]
This has been solved by removing those links entirely in #196
