### ISSUE TITLE
Search parameters: Array inequality misleading

### ISSUE THREAD

**Issue by johanneswuerbach** [contentful/slash-developers#197]
The description of the array inequality is misleading  https://www.contentful.com/developers/docs/references/content-delivery-api/#/reference/search-parameters/array-equalityinequality

> If one of the items in an Array field matches the value the field will match.

Allows the conclusion that that Entries are return when **one** of the array element does not match the search value, but the implementation will only return Entries where **none** of the array elements matches the search value.

**Comment by gaapt** [comment]
Created https://github.com/contentful/slash-developers/pull/200

**Comment by realityking** [comment]
Fixed by #328
