### ISSUE TITLE
Links section is not clear on include parameters

### ISSUE THREAD

**Issue by trodrigues** [contentful/slash-developers#198]
On https://www.contentful.com/developers/docs/references/content-delivery-api/#/reference/links/query-entries, two small things:
- The value of the parameter could maybe be `include_value` to make it more clear when looking at the listing of parameters
  ![2016-02-09 at 14 11](https://cloud.githubusercontent.com/assets/38177/12917034/207561de-cf37-11e5-945d-33a9ae2ed5a3.png)
- Response list of attributes does not list `includes` object which is retrieved for this case:

![2016-02-09 at 14 12](https://cloud.githubusercontent.com/assets/38177/12917070/68a5bf30-cf37-11e5-8db9-9efe7009634f.png)

I was going to submit a PR for this but in the second problem, it's currently using a partial for an empty array and I'm not sure how it could be extended.

**Comment by neonichu** [comment]
I think you could just use something like this:

```apib
- sys - System Attributes
    - type: Array - Type of Resource
- total: 0 (number) - Total number of resources matching
- skip: 0 (number) - Number of resources skipped
- limit: 100 (number) - Maximum number of resources in this response
- items (array) - Resources contained in the array
- includes - Included resources
    - Entries: Array - Included Entries
    - Assets: Array - Included Assets
```

**Comment by trodrigues** [comment]
Probably related to #202
