### ISSUE TITLE
Wrong parameter on space membership response

### ISSUE THREAD

**Issue by gaapt** [contentful/slash-developers#219]
In the example at  https://www.contentful.com/developers/docs/references/content-management-api/#/reference/space-memberships/space-membership/get-a-single-space-membership the user email is given, which is not the case.

**Comment by realityking** [comment]
That seems to be @sdepold's garden

**Comment by sdepold** [comment]
@gaapt Yep. Good catch.

It works like this: When you create a space membership initially, you have to provide an email address which is used to invite the user. From thereon you will never find the email property anymore but a `user` property instead with a link to the respective user. Can you change the docs accordingly?

**Comment by gaapt** [comment]
https://github.com/contentful/slash-developers/pull/245

**Comment by neonichu** [comment]
#245 has been merged.
