### ISSUE TITLE
Clarify retrieved spaces have a default limit of 25

### ISSUE THREAD

**Issue by gaapt** [contentful/slash-developers#269]

**Comment by neonichu** [comment]
We should also mention that the maximum `limit` for fetching spaces is 100.

**Comment by realityking** [comment]
This whole section should probably be reworded: https://www.contentful.com/developers/docs/references/content-delivery-api/#/reference/search-parameters/limit

It's basically only talking about entries and no other entity.

**Comment by realityking** [comment]
@ChrisChinchilla I saw https://github.com/contentful/slash-developers/commit/5af5c9532f662784e53c41bcd8617b8ddcc5a3eb which is better but still somewhat incomplete given the comment from @neonichu above. I'm reopening this but if you want I can open a separate ticket too :)

**Comment by floelhoeffel** [comment]
migrated to tp
