### ISSUE TITLE
Document API Keys

### ISSUE THREAD

**Issue by trodrigues** [contentful/slash-developers#285]
Api Keys are very very vaguely documented: https://www.contentful.com/developers/docs/references/content-management-api/#/reference/api-keys/get-all-api-keys

On top of that, we probably also have an endpoint to get a single API Key, and API keys can be updated (although there are some specific bits about this, like regenerating the key which might also need to be documented).

**Comment by realityking** [comment]
The first part has been addressed by #328. The second part (documenting the single API key endpoint) is still open.

**Comment by floelhoeffel** [comment]
moved to TP
