### ISSUE TITLE
Headers in webhook definitions

### ISSUE THREAD

**Issue by trodrigues** [contentful/slash-developers#287]
Two separate issues:
- The webhook_definitions "create a webhook" doesn't document custom headers in the payload parameters
- The webhooks_definition create/update parameters documentation documents headers but there seems to be a slight issue where there should also be a value 2 example:

![2016-05-24 at 13 52](https://cloud.githubusercontent.com/assets/38177/15502925/28f60b38-21b7-11e6-87dc-dabaa4d74d44.png)

**Comment by floelhoeffel** [comment]
migrated
