### ISSUE TITLE
Skipped webhook call test

### ISSUE THREAD

**Issue by madtrick** [contentful/slash-developers#289]
### Summary

We have had to disable a webhook call test (https://github.com/contentful/slash-developers/pull/279/files#diff-481015fa5d4d88dd9a9650804b24f4edR6) because it was breaking the test run. The reason for the failure was that the test was referencing an specific webhook call object and those are deleted after 1 month, therefore the call returned a `404` instead of the expected `200`.
#### What to do

Decide if we are fine with keeping this test as skipped or if we want to spend some time trying to find a workaround to do the call. @realityking [mentioned](https://github.com/contentful/slash-developers/pull/279#issuecomment-222473170) the possibility of triggering a webhook call, waiting, and after a while fetching the call id to use in the test.

**Comment by floelhoeffel** [comment]
@jelz what should we do with this? I guess it doesnt apply for doc-app?

**Comment by jelz** [comment]
Does not apply any longer.
