### ISSUE TITLE
Scrolling isn't possible with a trackpad

### ISSUE THREAD

**Issue by gaapt** [contentful/slash-developers#297]
Scrolling with a mac trackpad on the api documentation isn't possible due to nested scrollable panels

**Comment by TimBeyer** [comment]
I noticed that too. Usually resizing the browser window fixes it.

**Comment by realityking** [comment]
I'm keeping in touch with Apiary about this. They can't reproduce the issue so it's a bit of an uphill battle.

**Comment by realityking** [comment]
Apiary has managed to reproduce the issue. 😎  No word yet on a fix.

**Comment by ChrisChinchilla** [comment]
@gaapt @realityking This appears to be fixed…
