### ISSUE TITLE
Provide better descriptions for errors

### ISSUE THREAD

**Issue by gaapt** [contentful/slash-developers#303]
On https://www.contentful.com/developers/docs/references/errors/

There are incomplete and lacking descriptions for errors.

For example, on `403 Access Denied`, it doesn't explain how this could be related to specific circumstances (e.g. user has reached plan's limit)

**Comment by ChrisChinchilla** [comment]
@gaapt This looks like this is much better now, but let me know if you think more clarification is needed.
