### ISSUE TITLE
Lacking content type definition across GET requests

### ISSUE THREAD

**Issue by gaapt** [contentful/slash-developers#308]
The issue described by Tiago at https://github.com/contentful/slash-developers/issues/295 is spread across almost all other sections on GET requests (either incomplete or outright empty):

https://www.contentful.com/developers/docs/references/content-management-api/#/reference/spaces/spaces-collection/get-all-spaces-an-account-has-access-to

https://www.contentful.com/developers/docs/references/content-management-api/#/reference/entries/entries-collection/get-all-entries-of-a-space

https://www.contentful.com/developers/docs/references/content-management-api/#/reference/assets/assets-collection/get-all-assets-of-a-space

https://www.contentful.com/developers/docs/references/content-management-api/#/reference/assets/asset/get-a-single-asset

**Comment by neonichu** [comment]
All of the collection endpoints define empty arrays in the blueprint for simplicity's sake.

**Comment by ChrisChinchilla** [comment]
@gaapt based on the comment above, is this something you want to improve or not?
