### ISSUE TITLE
Broken link in CMA search parameters doc page

### ISSUE THREAD

**Issue by hlabas** [contentful/slash-developers#326]
On this page: https://www.contentful.com/developers/docs/references/content-management-api/#/reference/search-parameters
Clicking on the link: _See the *reference documentation for the Content Delivery API* for a list of search parameters_ has no effect (Cmd+Click opens the expected link)

Verified on Chrome

**Comment by realityking** [comment]
Error is within Apiary. I'll report it.

**Comment by realityking** [comment]
This has been fixed by Apiary.
