### ISSUE TITLE
Capitalization

### ISSUE THREAD

**Issue by grncdr** [contentful/slash-developers#35]
Currently, much/most of the documentation uses capitalization as a stylistic device for indicating that a word refers to a concrete entity or concept. Examples from [docs/concepts/data-model.md](https://github.com/contentful/slash-developers/blob/01721115ec1a7a97dfc8283f8babecc9e0c88e80/docs/concepts/data-model.md):

1. Content in Contentful is organized into Spaces, so that related resources for one project can be grouped together into one repository.

2. Assets have three fixed fields, name, description and the attached file, but the structure of Entries in your Space is defined in the Content Model.

This is visually jarring for many readers and it's not really clear why Some Things are capitalized.

## New style proposal

Until we have a full style guide for these docs, I'd propose the following.

1. The first time an entity or concept is named in a document, it should be italicized.
  - If that entity is not the subject of the current document, it should be followed by a parenthesized link to the document that explains what it means.
2. The name should be written using no decoration thereafter.

Given the above rules, our two examples become:

1. Content in Contentful is organized into _spaces_, so that related resources for one project can be grouped together into one repository.

2. Assets have three fixed fields, name, description and the attached file, but the structure of entries in your space is defined in the content model.

_Note: all of the special terms in example 2 were previously introduced._

**Comment by neonichu** [comment]
I think "first time" doesn't carry much meaning for a lot of our documentation, because people might jump in at any point in the middle, especially considering the reference docs. So I think whatever kind of markup we use, it should not depend on number of occurrences.

**Comment by grncdr** [comment]
I've made this change in #79, but without the "first time" highlighting. Need to have some thought around how to integrate "glossary content" without making everything links.

**Comment by grncdr** [comment]
Turns out near-universal consensus was on keeping the capitalization. Problem solved :+1:
