### ISSUE TITLE
Consistently use query params for authentication

### ISSUE THREAD

**Issue by neonichu** [contentful/slash-developers#37]
Currently, we use query params for the CDA/CPA blueprints, but headers for the CMA. This is because we need to overwrite the access token for the CMA tests, as the one in the documentation obviously can't be a working one or we'd give everyone write access.

The ideal solution would be for `dredd` to support overwriting query params, see apiaryio/dredd#251

**Comment by realityking** [comment]
AFAIK the CMA doesn't allow authentication with a query param. We could however change the CDA to use a header. Is that what you mean?

**Comment by neonichu** [comment]
CMA supports the same authentication options as the other APIs. Unfortunately, I'm not sure anymore what the reasoning was for this ticket, too bad I didn't include that when opening it 😞
