### ISSUE TITLE
Adding colour names to background colour definition? 

### ISSUE THREAD

**Issue by mariobodemann** [contentful/slash-developers#393]
Hey,

I think it would be nice to also have the specification on which colours can be used as the background. Trying, I found that 

https://images.contentful.com/cfexampleapi/3MZPnjZTIskAIIkuuosCss/382a48dfa2cb16c47aa2c72f7b23bf09/happycatw.jpg?r=100&bg=pink

actually produces a pink round rectangle.

 https://github.com/contentful/slash-developers/blob/master/apiary/images.apib#L182

**Comment by floelhoeffel** [comment]
migrated
