### ISSUE TITLE
Wrong endpoint - search on references

### ISSUE THREAD

**Issue by gaapt** [contentful/slash-developers#426]
on https://www.contentful.com/developers/docs/references/content-delivery-api/#/reference/search-parameters/search-on-references/search-on-references?console=1

it queries for `assets` of the spaces, while it should be `entries`, as:

`https://cdn.contentful.com/spaces/cfexampleapi/entries?access_token=b4c0n73n7fu1&content_type=cat&fields.bestFriend.sys.contentType.sys.id=cat&fields.bestFriend.fields.color=rainbow`

**Comment by ChrisChinchilla** [comment]
@gaapt Thanks! Aware of this and it's fixed, but waiting on a merge that I'm having issues with :(
