### ISSUE TITLE
Missing clear text content type id

### ISSUE THREAD

**Issue by mariobodemann** [contentful/slash-developers#440]
As stated in the text, specifying a content type id as human readable is desireable, sadly we fail short in our example our self. The rendered text looks like:

```
it's tidier to query for content_type=2PqfXUJwE8qSYKuM0U6w8M than
content_type=5KsDBWseXY6QegucYAoacS.
``` 

the culprit line is this one, sadly I do not quite understand how the matching and generation works.
https://github.com/contentful/slash-developers/blob/master/apiary/cma.apib#L217

Can we make it look something like
```
it's tidier to query for content_type=candy_bars than
content_type=5KsDBWseXY6QegucYAoacS.
``` 
?

**Comment by ChrisChinchilla** [comment]
@mariobodemann Hmm, I think this will have to wait until the example spaces have better ids, so maybe I will remove that line for now. Also moving this to docs-app repo.
