### ISSUE TITLE
Wrong <h2> header tags on list item

### ISSUE THREAD

**Issue by gaapt** [contentful/slash-developers#458]
https://www.contentful.com/developers/docs/concepts/locales/#contentful-will-only-use-the-content-of-the-fallback-locale-when-the-requested-one-is-not-present-in-the-entry-or-asset-ie-you-request-en-us-but-the-entry-has-only-content-for-de-de-this-means-that-values-like-null-or-an-empty-string--will-not-cause-the-system-to-use-the-value-of-the-fallback-locale-this-can-only-be-set-via-the-api-and-not-with-the-web-app-or-sdks

**Comment by ChrisChinchilla** [comment]
Fixed in https://github.com/contentful/slash-developers/pull/459
