### ISSUE TITLE
Sync API deletions are actually unpublishes

### ISSUE THREAD

**Issue by andrefs** [contentful/slash-developers#470]
On the Synchronization section https://www.contentful.com/developers/docs/references/content-delivery-api/#/reference/synchronization we mention several times document deletion. 

However, these are actually unpublishes (Sync CDA is unaware of actual deletions), but that idea is not very clear when you read the docs.

**Comment by floelhoeffel** [comment]
Its actually the other way around - on sync there is only deletions (no matter if the cma operation was delete or unpublish).
