### ISSUE TITLE
Wrong request URL in search by references

### ISSUE THREAD

**Issue by gaapt** [contentful/slash-developers#476]
https://www.contentful.com/developers/docs/references/content-delivery-api/#/reference/search-parameters/search-on-references

the request URL is 

http://cdn.contentful.com/spaces/yadj1kx9rmg0/entries?access_token=fdb4e7a3102747a02ea69ebac5e282b9e44d28fb340f778a4f5e788625a61abe&content_type=2PqfXUJwE8qSYKuM0U6w8M&fields.brand.sys.contentType.sys.id=sFzTZbSuM8coEwygeUYes&fields.brandcompanyNameLemnos

whose parameter `fields.brandcompanyNameLemnos` doesn't include a value, as in the example of this same section (`fields.brand.fields.companyName[match]=Lemnos`)

**Comment by floelhoeffel** [comment]
moved to doc-app, thanks for finding this!
