### ISSUE TITLE
Explanation of roles constraints and examples

### ISSUE THREAD

**Issue by gaapt** [contentful/slash-developers#478]
Section: https://www.contentful.com/developers/docs/references/content-management-api/#/reference/roles

It's not clear what values can be used with each constraint (e.g. `"doc": "sys.contentType.sys.id"`) and there are not enough examples demonstrating what can be achieved while creating roles directly through the API, and how it differs from the Web Interface.

**Comment by floelhoeffel** [comment]
Moving this to TP - thanks!
