### ISSUE TITLE
Parameter description in bounding rectangle wrong

### ISSUE THREAD

**Issue by johanneswuerbach** [contentful/slash-developers#58]
The docs state that querying in a bounding rectangle requires the coords to provided like:

> This will return entries where fields.center is within the rectangle with:
Bottom left corner: latitude 1, longitude 2
Top right corner: latitude 3, longitude 4

I think the first two parameters are top left and the last two bottom right.

**Comment by johanneswuerbach** [comment]
This paragraph http://docs.contentfulcda.apiary.io/#reference/search-parameters/locations-in-bounding-rectangle/query-entries is also slightly confusing as it is mixes bounding box and distance querying into a single paragraph.

**Comment by neonichu** [comment]
Yah, since both use the same parameter name, they can't be documented in separate sections in a blueprint. Maybe switching to a bullet list could help make it clearer that these are two different uses of the same parameter?

**Comment by neonichu** [comment]
I guess this hasn't been so widely used so far, considering the parameter description comes from the original docs 😂

**Comment by gaapt** [comment]
Created https://github.com/contentful/slash-developers/pull/108
