### ISSUE TITLE
Use actual characters in examples instead of entities

### ISSUE THREAD

**Issue by trodrigues** [contentful/slash-developers#61]
In examples such as http://docs.contentfulcda.apiary.io/#reference/search-parameters/inclusion/query-entries we have things like `sys.id%5Bin%5D=value`

We should probably replace those entities with the actual characters to make it more readable.

**Comment by neonichu** [comment]
I agree, but IIRC, API blueprint didn't support that — but I'll double-check it.

**Comment by neonichu** [comment]
API blueprint indeed doesn't support this, the linting already warns about it and suggests to use percent encoding.
