### ISSUE TITLE
Broken links at the very top of the documentation

### ISSUE THREAD

**Issue by hungryblank** [contentful/slash-developers#65]
http://docs.contentfulcda.apiary.io/#introduction/contentful-is-an-api-first-cms-for-delivering-content-to-any-device.

 says

```
Visit Contentful developer center for more documentation and developer tools.See also references to other Contentful APIs:

* Content Delivery API
* Content Management API
* Content Preview API
* Images API
```

All links to these APIs point to error pages.

**Comment by neonichu** [comment]
This is fixed now since Apiary embedding got merged to the main website.
