### ISSUE TITLE
Change order of Content Type and Entries on documentation

### ISSUE THREAD

**Issue by gaapt** [contentful/slash-developers#66]
The documentation describes what a Content Type is before explaining the concept of an Entry, which may confuse users. It'd probably make more sense to invert them and include a link to the following Content Type section.

**Comment by neonichu** [comment]
I think this is fine the way it currently is, because users have to first create CTs and then entries. The conceptual docs (<https://www.contentful.com/developers/docs/concepts/data-model/>) indeed reverse the order of appearance because it is easier to understand.
