### ISSUE TITLE
Search parameter examples need content_type

### ISSUE THREAD

**Issue by trodrigues** [contentful/slash-developers#72]
There are some search parameter examples where we search a specific field (`fields.description=something`) but we don't make it explicit that you always need to specify a content type as well for those to work.

**Comment by neonichu** [comment]
hm, as far as I can see, all queries that need that parameter have it listed as `required` (e.g. <https://github.com/contentful/slash-developers/blob/master/apiary/cda-body.apib#L335>) — can you point to specific ones you think are wrong? Or do you think we should make it explicit in the prose for those queries which need it?

**Comment by trodrigues** [comment]
I don't know if I'm missing something but looking at the generated docs nothing there tells me this is required:

![2015-10-09 at 16 35](https://cloud.githubusercontent.com/assets/38177/10396635/e60b2a0e-6ea3-11e5-9427-b32e53ac5f62.png)

Also, I think a textual description of it being required for those cases would still be good, rather than just show it as required on the list of parameters and people not understanding the reason why.

**Comment by trodrigues** [comment]
Ah, I just noticed this is explained on https://www.contentful.com/developers/docs/references/content-delivery-api/#/reference/search-parameters

> When querying Entries and using search filters based on fields or ordering by fields you must specify this parameter.

But yeah, still looking at that example and if I jump straight to it, I would have no idea of this.

**Comment by neonichu** [comment]
ugh, you're right, I was just looking at the Markdown, not at the rendered output. It seems like the `required` vs. `optional` nature of URL parameters is not actually shown anywhere :disappointed:

**Comment by gaapt** [comment]
It's somewhat 'intuitive' that it's required, but it'd definitely make it more explicit.

**Comment by gaapt** [comment]
A commit on in has been merged https://github.com/contentful/slash-developers/commit/79dd62b6e176232bb63b71cc39550bf59d66152c
