### ISSUE TITLE
Change value of example ID 

### ISSUE THREAD

**Issue by gaapt** [contentful/slash-developers#76]
By using IDs like 'cat' and 'nyancat'  some users can assume they should use the name, not ID, of a resource. 

http://docs.contentfulcda.apiary.io/#reference/content-types/content-type/get-a-single-content-type

**Comment by neonichu** [comment]
This is a duplicate of #16 — the main issue is that we need to recreate the example and make sure we update all of our documentation everywhere to use the new IDs.
