### ISSUE TITLE
Improve awareness of third party libraries and tools

### ISSUE THREAD

**Issue by trodrigues** [contentful/slash-developers#81]
This comes from a conversation I was having with Peter but also something I've noticed before: a lot of people are not aware of the existence of https://github.com/contentful-labs/awesome-contentful or even how to find it, and they keep asking us about SDKs for languages which exist there, but they can also not find them on the website.

We link to that repo on both https://www.contentful.com/developers/docs/code/tools/ and https://www.contentful.com/developers/docs/code/libraries/ under the **Unofficial** headline at the bottom but just give a very short description.

My idea would be to replace that description with something like:
> Apart from the tools/libraries above, there are others developed by our community, which you can find at [awesome-contentful](https://github.com/contentful-labs/awesome-contentful).
> There you can find integrations for other languages and platforms such as PHP and .NET, or integrations with frameworks, static site generators and other tools.
> If you want to know how to use Contentful with a specific framework or tool, not listed above, have a look at the [awesome-contentful](https://github.com/contentful-labs/awesome-contentful) list.

**Comment by dlitvakb** [comment]
:+1:

**Comment by gaapt** [comment]
+1

**Comment by neonichu** [comment]
:+1:

**Comment by gaapt** [comment]
Created PR https://github.com/contentful/slash-developers/pull/89 .

:+1:  / :-1:  ?

**Comment by grncdr** [comment]
:+1:
