### ISSUE TITLE
left hand site bar link to collection resources an pagination doesn't work

### ISSUE THREAD

**Issue by hungryblank** [contentful/slash-developers#86]
Left menu introduction section when clicking on `Collection Resources & Pagination` the page just scrolls to the very top.

http://docs.contentfulcda.apiary.io/#introduction/collection-resources-&amp;-pagination

maybe because of the `&amp;` entity?

**Comment by grncdr** [comment]
Fixed by 206e1c73c2fc2ae2d7ab23fff3a31e0eb907f605
