### ISSUE TITLE
ContentType field types missing in the CMA docs

### ISSUE THREAD

**Issue by johanneswuerbach** [contentful/slash-developers#93]
The CMA docs don't include a list of possible field types. I would except to find possible allowed values here https://www.contentful.com/developers/docs/references/content-management-api/#/reference/content-types in the same format it is done in the CDA docs https://www.contentful.com/developers/docs/references/content-delivery-api/#/reference/content-types/content-type

**Comment by gaapt** [comment]
Created https://github.com/contentful/slash-developers/pull/96
