### ISSUE TITLE
ContentTypeField Array type without examples

### ISSUE THREAD

**Issue by johanneswuerbach** [contentful/slash-developers#94]
https://www.contentful.com/developers/docs/references/content-delivery-api/#/reference/content-types/content-type mentions an array type, but doesn't provide any example how a field of that type is defined.

Something like that would be helpful:
`{ id: 'names', name: 'names', type: 'Array', items: { type: 'Symbol' } }`

**Comment by sdepold** [comment]
+1 

It's not understandable at all right now.

**Comment by gaapt** [comment]
https://github.com/contentful/slash-developers/blob/3c00f1a56709622e6d4cf0eede7f1d3c9e78ddef/apiary/_partials/content-types-description.md#array-fields has been added
