### ISSUE TITLE
Clarify that `include` only affects links to assets and spaces

### ISSUE THREAD

**Issue by realityking** [contentful/slash-developers#99]
Since the connection to a Space or Content Type looks identical to a link, it could be thought those are affected by `include` as well.

**Comment by grncdr** [comment]
This is a good point, the docs should clarify that only links in `fields` are followed.

**Comment by neonichu** [comment]
Currently they state only links to entries are followed: <https://github.com/contentful/slash-developers/blob/master/apiary/cda-body.apib#L617> — this should probably be changed to mention assets as well :)

**Comment by gaapt** [comment]
Created https://github.com/contentful/slash-developers/pull/111
